= Harman Kardon Aura Speaker Protocol Analysis

This project focuses on reverse-engineering the communication protocol of the Harman Kardon Aura Plus speaker. +
The goal is to control the speaker’s playback (pause, play, volume) and settings (bass, EQ) through a custom integration in Home Assistant, eliminating the need for the official app.


I have a Harman Kardon Aura Plus speaker and want to reverse-engineer the protocol it uses with its app (Bass, EQ, Volume) and control playback (Pause, Play, Set Volume) and integrate it into Home Assistant, eliminating the need for the app. +
The speaker connects via Wi-Fi, and the HK Remote app controls bass and EQ settings not available elsewhere.

NOTE: This is a personal project and should be used only for personal purposes.

== Initial attempts
I’ve captured the packets from the speaker (172.16.1.68), the iPhone with the app installed on it (172.16.1.69), and the Mac that was streaming the music (172.16.1.66) with `sudo ettercap -T -M arp:remote /172.16.1.66// /172.16.1.68// /172.16.1.69// -w packets.pcap` and analyzed the pcap file with WireShark.

I also recreate the different calls with Postman to better understand the protocol and test the commands.

Looking at any packets that might be immediately relevant, we get this:

----
Wed Jan 15 15:45:54 2025 [442538]
TCP  172.16.1.69:62528 --> 172.16.1.68:8080 | AP (202)
GET /description.xml HTTP/1.1.
Host: 172.16.1.68:8080.
Date: Wed, 15 Jan 2025 03:45:39 GMT.
Connection: Keep-Alive.
User-Agent: NFLC/2.2 UPnP/1.0 DLNADOC/1.50.
friendlyName.dlna.org: Access_NFLC/2.2.

Wed Jan 15 15:45:54 2025 [144199]
UDP  172.16.1.68:3911 --> 172.16.1.69:63631 |  (226)
HTTP/1.1 200 OK.
CACHE-CONTROL: max-age=1800.
EXT:.
LOCATION: http://172.16.1.68:8080/description.xml.
SERVER: KnOS/3.2 UPnP/1.0 DMP/3.5.
ST: upnp:rootdevice.
USN: uuid:abc123-def456-ghi789-jkl012-mno345678901::upnp:rootdevice.
----
(Further details regarding the description.xml can be found in the link:xml_files[])

== Setup
. Make sure your device is connected to the same network as the Harman Kardon speaker. +

. Clone this repository: +
----
    git clone https://github.com/vakintosh/hk_aura_protocol_analysis +
----

== Available Commands

The following commands are available to control the Harman Kardon Aura speaker. +
These commands can be found under link:Harman_Kardon_Remote[]

=== set_system_volume
This command sets the system volume to a specified level. +
The volume level is specified in the <para> tag within the XML payload. +
The minimum value is 0 and the maximum value is 100.
----
python hk_app.py set_system_volume --para 0
----

=== set_bass_level
This command sets the bass level to a specified value. The bass level is specified in the <para> tag within the XML payload. The minimum value is 0 and the maximum value is 100.
----
python hk_app.py set_bass_level --para 0
----

=== set_EQ_mode to Stereo Widening
This command sets the EQ mode to "Stereo Widening". +
The EQ mode is specified in the <para> tag within the XML payload.
----
python hk_app.py set_EQ_mode --para on
----

=== set_EQ_mode to Basic
This command sets the EQ mode to "Basic". +
The EQ mode is specified in the <para> tag within the XML payload.
----
python hk_app.py set_EQ_mode --para off
----

=== heart-alive
This command sends a heartbeat signal to keep the connection alive. +
It does not require any parameters in the <para> tag within the XML payload.
----
python hk_app.py heart-alive
----

== Next steps

The next steps would be to implement additional playback controls such as:
* Play
* Pause
* Stop
* Rewind
* Previous track
* Next track

Additionally, integrating these controls into Home Assistant to create a seamless user experience without needing the official app would be beneficial.
