// HK app to Speaker

= Available Actions

This list includes some actions available in the official app. +
However, there may be some hidden actions not provided by the app. +
If you know or find some new actions, please open a PR. +

The port 10025 is used for the connection to the Harman Kardon Aura speaker. +
This port is specific to the speaker's control interface and is used to send commands in XML format.

== set_system_volume
This command sets the system volume to a specified level. +
The volume level is specified in the <para> tag within the XML payload. +
The minimum value is 0 and the maximum value is 100. +
[,xml]
----
'<?xml version="1.0" encoding="UTF-8"?>
<harman>
  <mm>
    <common>
      <control>
        <name>set_system_volume</name>
        <zone>Main Zone</zone>
        <para>0</para>
      </control>
    </common>
  </mm>
</harman>
----

== set_bass_level
This command sets the bass level to a specified value. +
The bass level is specified in the <para> tag within the XML payload. +
The minimum value is 0 and the maximum value is 100. +
[,xml]
----
'<?xml version="1.0" encoding="UTF-8"?>
<harman>
  <mm>
    <common>
      <control>
        <name>set_bass_level</name>
        <zone>Main Zone</zone>
        <para>0</para>
      </control>
    </common>
  </mm>
</harman>
----


== set_EQ_mode to Stereo Widening
This command sets the EQ mode to "Stereo Widening". +
The EQ mode is specified in the <para> tag within the XML payload. +
[,xml]
----
'<?xml version="1.0" encoding="UTF-8"?>
<harman>
  <mm>
    <common>
      <control>
        <name>set_EQ_mode</name>
        <zone>Main Zone</zone>
        <para>Stereo Widening</para>
      </control>
    </common>
  </mm>
</harman>'
----

== set_EQ_mode to Basic
This command sets the EQ mode to "Basic". +
The EQ mode is specified in the <para> tag within the XML payload. +
[,xml]
----
'<?xml version="1.0" encoding="UTF-8"?>
<harman>
  <mm>
    <common>
      <control>
        <name>set_EQ_mode</name>
        <zone>Main Zone</zone>
        <para>Basic</para>
      </control>
    </common>
  </mm>
</harman>'
----

== heart-alive
This command sends a heartbeat signal to keep the connection alive. +
It does not require any parameters in the <para> tag within the XML payload. +
[,xml]
----
'<?xml version="1.0" encoding="UTF-8"?>
<harman>
  <mm>
    <common>
      <control>
        <name>heart-alive</name>
        <zone></zone>
        <para></para>
      </control>
    </common>
  </mm>
</harman>'
----

== Power-off
This command powers off the Harman Kardon Aura speaker. +
It does not require any parameters in the <para> tag within the XML payload. +
[,xml]
----
'<?xml version="1.0" encoding="UTF-8"?>
<harman>
  <mm>
    <common>
      <control>
        <name>power-off</name>
        <zone>Main Zone</zone>
        <para></para>
      </control>
    </common>
  </mm>
</harman>''
----
